[
  {"lib/year2020/day07.ex", "Type mismatch in call without opaque term in traverse."},
  {"lib/year2020/day07.ex", "Type mismatch in call without opaque term in size."},
  {"lib/year2020/day07.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/year2020/day07.ex", "Type mismatch in call without opaque term in union."},
  {"lib/year2021/day08.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/year2021/day08.ex", "Type mismatch in call with opaque term in build_group."},
  {"lib/year2021/day09.ex", "Type mismatch in call without opaque term in traverse_visited."},
  {"lib/year2021/day09.ex", "Type mismatch in call with opaque term in traverse."},
  {"lib/year2021/day09.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/year2021/day09.ex", "Type mismatch in call without opaque term in union."},
  {"lib/year2021/day11.ex", "Type mismatch in call without opaque term in simulate_rounds."},
  {"lib/year2021/day12.ex", "Type mismatch in call without opaque term in traverse."},
  {"lib/year2021/day20.ex", "Type mismatch in call without opaque term in enhance_image."},
  {"lib/year2021/day20.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/year2021/day20.ex", "Type mismatch in call without opaque term in prepare_continue."},
  {"lib/year2021/day20.ex", "Type mismatch in call without opaque term in union."},
  {"lib/year2021/day23.ex", "Type mismatch in call without opaque term in before_find."},
  {"lib/year2021/day23.ex", "Type mismatch in call without opaque term in member?."},
  {"lib/year2023/day22.ex", "Type mismatch in call without opaque term in size."},
  {"lib/year2023/day22.ex", "Type mismatch in call without opaque term in put."},
  {"lib/year2023/day22.ex", "Type mismatch in call with opaque term in process_chain."},
]
