
name: Elixir CI

on: [push, pull_request, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest

        environment: troodon

        strategy:
            matrix:
                elixir: ["1.18.0"] # replace with latest
                otp: [latest]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Elixir
              uses: erlef/setup-beam@v1
              with:
                  elixir-version: ${{ matrix.elixir }}
                  otp-version: ${{ matrix.otp }}

            - name: Install dependencies
              run: mix deps.get

            - name: Run tests
              run: mix test
              env:
                TESLA_COMPLETE_URL: ${{ secrets.TESLA_COMPLETE_URL }}
                SESSION_TOKEN: ${{ secrets.SESSION_TOKEN }}
                DAY20241204_PART_1: ${{ secrets.DAY20241204_PART_1 }}
                DAY20241204_PART_2: ${{ secrets.DAY20241204_PART_2 }}
                DAY20241205_PART_1: ${{ secrets.DAY20241205_PART_1 }}
                DAY20241205_PART_2: ${{ secrets.DAY20241205_PART_2 }}
                DAY20241206_PART_1: ${{ secrets.DAY20241206_PART_1 }}
                DAY20241206_PART_2: ${{ secrets.DAY20241206_PART_2 }}
                DAY20241207_PART_1: ${{ secrets.DAY20241207_PART_1 }}
                DAY20241207_PART_2: ${{ secrets.DAY20241207_PART_2 }}
                DAY20241208_PART_1: ${{ secrets.DAY20241208_PART_1 }}
                DAY20241208_PART_2: ${{ secrets.DAY20241208_PART_2 }}
                DAY20241209_PART_1: ${{ secrets.DAY20241209_PART_1 }}
                DAY20241209_PART_2: ${{ secrets.DAY20241209_PART_2 }}
                DAY20241210_PART_1: ${{ secrets.DAY20241210_PART_1 }}
                DAY20241210_PART_2: ${{ secrets.DAY20241210_PART_2 }}
                DAY20241211_PART_1: ${{ secrets.DAY20241211_PART_1 }}
                DAY20241211_PART_2: ${{ secrets.DAY20241211_PART_2 }}
                DAY20241212_PART_1: ${{ secrets.DAY20241212_PART_1 }}
                DAY20241212_PART_2: ${{ secrets.DAY20241212_PART_2 }}
                DAY20241213_PART_1: ${{ secrets.DAY20241213_PART_1 }}
                DAY20241213_PART_2: ${{ secrets.DAY20241213_PART_2 }}
                DAY20241214_PART_1: ${{ secrets.DAY20241214_PART_1 }}
                DAY20241214_PART_2: ${{ secrets.DAY20241214_PART_2 }}
                DAY20241215_PART_1: ${{ secrets.DAY20241215_PART_1 }}
                DAY20241215_PART_2: ${{ secrets.DAY20241215_PART_2 }}
                DAY20241216_PART_1: ${{ secrets.DAY20241216_PART_1 }}
                DAY20241216_PART_2: ${{ secrets.DAY20241216_PART_2 }}
                DAY20241217_PART_1: ${{ secrets.DAY20241217_PART_1 }}
                DAY20241217_PART_2: ${{ secrets.DAY20241217_PART_2 }}
                DAY20241218_PART_1: ${{ secrets.DAY20241218_PART_1 }}
                DAY20241218_PART_2: ${{ secrets.DAY20241218_PART_2 }}
                DAY20241219_PART_1: ${{ secrets.DAY20241219_PART_1 }}
                DAY20241219_PART_2: ${{ secrets.DAY20241219_PART_2 }}
                DAY20241220_PART_1: ${{ secrets.DAY20241220_PART_1 }}
                DAY20241220_PART_2: ${{ secrets.DAY20241220_PART_2 }}
                DAY202412xx_PART_1: ${{ secrets.DAY202412xx_PART_1 }}
                DAY202412xx_PART_2: ${{ secrets.DAY202412xx_PART_2 }}
