name: Elixir CI

on: [push, pull_request, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest

        environment: troodon

        strategy:
            matrix:
                elixir: [latest]
                otp: [latest]

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Elixir
              uses: erlef/setup-beam@v1
              with:
                  elixir-version: ${{ matrix.elixir }}
                  otp-version: ${{ matrix.otp }}

            - name: Install dependencies
              run: mix deps.get

            - name: Compile
              run: mix compile
